/*
 * Imgur API
 * Imgur's API exposes the entire Imgur infrastructure via a standardized programmatic interface. Using Imgur's API, you can do just about anything you can do on imgur.com, while using your programming language of choice.
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.imgur.api;

import team.polytech.imgur.model.AccountImagesResponse;
import team.polytech.imgur.model.AccountResponse;
import team.polytech.imgur.model.BasicInt32Response;
import team.polytech.imgur.model.ImageResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountApi
 */
@Ignore
public class AccountApiTest {

    private final AccountApi api = new AccountApi();

    
    /**
     * Get information about an account.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountTest() {
        String userName = null;

        AccountResponse response = api.getAccount(userName);

        // TODO: test validations
    }
    
    /**
     * Get an image of an account.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountImageTest() {
        String imageHash = null;
        String userName = null;

        ImageResponse response = api.getAccountImage(imageHash, userName);

        // TODO: test validations
    }
    
    /**
     * Get images of an account.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountImagesTest() {
        String userName = null;

        AccountImagesResponse response = api.getAccountImages(userName);

        // TODO: test validations
    }
    
    /**
     * Get images count of an account.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountImagesCountTest() {
        String userName = null;

        BasicInt32Response response = api.getAccountImagesCount(userName);

        // TODO: test validations
    }
    
}
