/*
 * Imgur API
 * Imgur's API exposes the entire Imgur infrastructure via a standardized programmatic interface. Using Imgur's API, you can do just about anything you can do on imgur.com, while using your programming language of choice.
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package team.polytech.imgur.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Image
 */
@JsonPropertyOrder({
  Image.JSON_PROPERTY_ACCOUNT_ID,
  Image.JSON_PROPERTY_ACCOUNT_URL,
  Image.JSON_PROPERTY_AD_TYPE,
  Image.JSON_PROPERTY_AD_URL,
  Image.JSON_PROPERTY_ANIMATED,
  Image.JSON_PROPERTY_BANDWIDTH,
  Image.JSON_PROPERTY_DELETEHASH,
  Image.JSON_PROPERTY_DATETIME,
  Image.JSON_PROPERTY_DESCRIPTION,
  Image.JSON_PROPERTY_FAVORITE,
  Image.JSON_PROPERTY_HEIGHT,
  Image.JSON_PROPERTY_ID,
  Image.JSON_PROPERTY_IN_GALLERY,
  Image.JSON_PROPERTY_IN_MOST_VIRAL,
  Image.JSON_PROPERTY_IS_AD,
  Image.JSON_PROPERTY_LINK,
  Image.JSON_PROPERTY_NAME,
  Image.JSON_PROPERTY_NSFW,
  Image.JSON_PROPERTY_SECTION,
  Image.JSON_PROPERTY_SIZE,
  Image.JSON_PROPERTY_TAGS,
  Image.JSON_PROPERTY_TITLE,
  Image.JSON_PROPERTY_TYPE,
  Image.JSON_PROPERTY_VIEWS,
  Image.JSON_PROPERTY_VOTE,
  Image.JSON_PROPERTY_WIDTH
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-26T20:01:36.060885+03:00[Europe/Moscow]")
public class Image {
  public static final String JSON_PROPERTY_ACCOUNT_ID = "account_id";
  private Integer accountId;

  public static final String JSON_PROPERTY_ACCOUNT_URL = "account_url";
  private String accountUrl;

  public static final String JSON_PROPERTY_AD_TYPE = "ad_type";
  private Integer adType;

  public static final String JSON_PROPERTY_AD_URL = "ad_url";
  private String adUrl;

  public static final String JSON_PROPERTY_ANIMATED = "animated";
  private Boolean animated;

  public static final String JSON_PROPERTY_BANDWIDTH = "bandwidth";
  private Integer bandwidth;

  public static final String JSON_PROPERTY_DELETEHASH = "deletehash";
  private String deletehash;

  public static final String JSON_PROPERTY_DATETIME = "datetime";
  private Integer datetime;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_FAVORITE = "favorite";
  private Boolean favorite;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  private Integer height;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_IN_GALLERY = "in_gallery";
  private Boolean inGallery;

  public static final String JSON_PROPERTY_IN_MOST_VIRAL = "in_most_viral";
  private Boolean inMostViral;

  public static final String JSON_PROPERTY_IS_AD = "is_ad";
  private Boolean isAd;

  public static final String JSON_PROPERTY_LINK = "link";
  private String link;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_NSFW = "nsfw";
  private Boolean nsfw;

  public static final String JSON_PROPERTY_SECTION = "section";
  private String section;

  public static final String JSON_PROPERTY_SIZE = "size";
  private Integer size;

  public static final String JSON_PROPERTY_TAGS = "tags";
  private List<String> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_VIEWS = "views";
  private Integer views;

  public static final String JSON_PROPERTY_VOTE = "vote";
  private String vote;

  public static final String JSON_PROPERTY_WIDTH = "width";
  private Integer width;

  public Image() {
  }

  public Image accountId(Integer accountId) {
    
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAccountId() {
    return accountId;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountId(Integer accountId) {
    this.accountId = accountId;
  }


  public Image accountUrl(String accountUrl) {
    
    this.accountUrl = accountUrl;
    return this;
  }

   /**
   * Get accountUrl
   * @return accountUrl
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountUrl() {
    return accountUrl;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountUrl(String accountUrl) {
    this.accountUrl = accountUrl;
  }


  public Image adType(Integer adType) {
    
    this.adType = adType;
    return this;
  }

   /**
   * Get adType
   * @return adType
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AD_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getAdType() {
    return adType;
  }


  @JsonProperty(JSON_PROPERTY_AD_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAdType(Integer adType) {
    this.adType = adType;
  }


  public Image adUrl(String adUrl) {
    
    this.adUrl = adUrl;
    return this;
  }

   /**
   * Get adUrl
   * @return adUrl
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AD_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAdUrl() {
    return adUrl;
  }


  @JsonProperty(JSON_PROPERTY_AD_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAdUrl(String adUrl) {
    this.adUrl = adUrl;
  }


  public Image animated(Boolean animated) {
    
    this.animated = animated;
    return this;
  }

   /**
   * Get animated
   * @return animated
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ANIMATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getAnimated() {
    return animated;
  }


  @JsonProperty(JSON_PROPERTY_ANIMATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAnimated(Boolean animated) {
    this.animated = animated;
  }


  public Image bandwidth(Integer bandwidth) {
    
    this.bandwidth = bandwidth;
    return this;
  }

   /**
   * Get bandwidth
   * @return bandwidth
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BANDWIDTH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getBandwidth() {
    return bandwidth;
  }


  @JsonProperty(JSON_PROPERTY_BANDWIDTH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBandwidth(Integer bandwidth) {
    this.bandwidth = bandwidth;
  }


  public Image deletehash(String deletehash) {
    
    this.deletehash = deletehash;
    return this;
  }

   /**
   * Get deletehash
   * @return deletehash
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETEHASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeletehash() {
    return deletehash;
  }


  @JsonProperty(JSON_PROPERTY_DELETEHASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletehash(String deletehash) {
    this.deletehash = deletehash;
  }


  public Image datetime(Integer datetime) {
    
    this.datetime = datetime;
    return this;
  }

   /**
   * Get datetime
   * @return datetime
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DATETIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getDatetime() {
    return datetime;
  }


  @JsonProperty(JSON_PROPERTY_DATETIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDatetime(Integer datetime) {
    this.datetime = datetime;
  }


  public Image description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public Image favorite(Boolean favorite) {
    
    this.favorite = favorite;
    return this;
  }

   /**
   * Get favorite
   * @return favorite
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FAVORITE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getFavorite() {
    return favorite;
  }


  @JsonProperty(JSON_PROPERTY_FAVORITE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFavorite(Boolean favorite) {
    this.favorite = favorite;
  }


  public Image height(Integer height) {
    
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getHeight() {
    return height;
  }


  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHeight(Integer height) {
    this.height = height;
  }


  public Image id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public Image inGallery(Boolean inGallery) {
    
    this.inGallery = inGallery;
    return this;
  }

   /**
   * Get inGallery
   * @return inGallery
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IN_GALLERY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getInGallery() {
    return inGallery;
  }


  @JsonProperty(JSON_PROPERTY_IN_GALLERY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInGallery(Boolean inGallery) {
    this.inGallery = inGallery;
  }


  public Image inMostViral(Boolean inMostViral) {
    
    this.inMostViral = inMostViral;
    return this;
  }

   /**
   * Get inMostViral
   * @return inMostViral
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IN_MOST_VIRAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getInMostViral() {
    return inMostViral;
  }


  @JsonProperty(JSON_PROPERTY_IN_MOST_VIRAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInMostViral(Boolean inMostViral) {
    this.inMostViral = inMostViral;
  }


  public Image isAd(Boolean isAd) {
    
    this.isAd = isAd;
    return this;
  }

   /**
   * Get isAd
   * @return isAd
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_AD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsAd() {
    return isAd;
  }


  @JsonProperty(JSON_PROPERTY_IS_AD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsAd(Boolean isAd) {
    this.isAd = isAd;
  }


  public Image link(String link) {
    
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLink() {
    return link;
  }


  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLink(String link) {
    this.link = link;
  }


  public Image name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public Image nsfw(Boolean nsfw) {
    
    this.nsfw = nsfw;
    return this;
  }

   /**
   * Get nsfw
   * @return nsfw
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NSFW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNsfw() {
    return nsfw;
  }


  @JsonProperty(JSON_PROPERTY_NSFW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNsfw(Boolean nsfw) {
    this.nsfw = nsfw;
  }


  public Image section(String section) {
    
    this.section = section;
    return this;
  }

   /**
   * Get section
   * @return section
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSection() {
    return section;
  }


  @JsonProperty(JSON_PROPERTY_SECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSection(String section) {
    this.section = section;
  }


  public Image size(Integer size) {
    
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSize() {
    return size;
  }


  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSize(Integer size) {
    this.size = size;
  }


  public Image tags(List<String> tags) {
    
    this.tags = tags;
    return this;
  }

  public Image addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTags(List<String> tags) {
    this.tags = tags;
  }


  public Image title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(String title) {
    this.title = title;
  }


  public Image type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(String type) {
    this.type = type;
  }


  public Image views(Integer views) {
    
    this.views = views;
    return this;
  }

   /**
   * Get views
   * @return views
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VIEWS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getViews() {
    return views;
  }


  @JsonProperty(JSON_PROPERTY_VIEWS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setViews(Integer views) {
    this.views = views;
  }


  public Image vote(String vote) {
    
    this.vote = vote;
    return this;
  }

   /**
   * Get vote
   * @return vote
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVote() {
    return vote;
  }


  @JsonProperty(JSON_PROPERTY_VOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVote(String vote) {
    this.vote = vote;
  }


  public Image width(Integer width) {
    
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getWidth() {
    return width;
  }


  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWidth(Integer width) {
    this.width = width;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Image image = (Image) o;
    return Objects.equals(this.accountId, image.accountId) &&
        Objects.equals(this.accountUrl, image.accountUrl) &&
        Objects.equals(this.adType, image.adType) &&
        Objects.equals(this.adUrl, image.adUrl) &&
        Objects.equals(this.animated, image.animated) &&
        Objects.equals(this.bandwidth, image.bandwidth) &&
        Objects.equals(this.deletehash, image.deletehash) &&
        Objects.equals(this.datetime, image.datetime) &&
        Objects.equals(this.description, image.description) &&
        Objects.equals(this.favorite, image.favorite) &&
        Objects.equals(this.height, image.height) &&
        Objects.equals(this.id, image.id) &&
        Objects.equals(this.inGallery, image.inGallery) &&
        Objects.equals(this.inMostViral, image.inMostViral) &&
        Objects.equals(this.isAd, image.isAd) &&
        Objects.equals(this.link, image.link) &&
        Objects.equals(this.name, image.name) &&
        Objects.equals(this.nsfw, image.nsfw) &&
        Objects.equals(this.section, image.section) &&
        Objects.equals(this.size, image.size) &&
        Objects.equals(this.tags, image.tags) &&
        Objects.equals(this.title, image.title) &&
        Objects.equals(this.type, image.type) &&
        Objects.equals(this.views, image.views) &&
        Objects.equals(this.vote, image.vote) &&
        Objects.equals(this.width, image.width);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, accountUrl, adType, adUrl, animated, bandwidth, deletehash, datetime, description, favorite, height, id, inGallery, inMostViral, isAd, link, name, nsfw, section, size, tags, title, type, views, vote, width);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Image {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    accountUrl: ").append(toIndentedString(accountUrl)).append("\n");
    sb.append("    adType: ").append(toIndentedString(adType)).append("\n");
    sb.append("    adUrl: ").append(toIndentedString(adUrl)).append("\n");
    sb.append("    animated: ").append(toIndentedString(animated)).append("\n");
    sb.append("    bandwidth: ").append(toIndentedString(bandwidth)).append("\n");
    sb.append("    deletehash: ").append(toIndentedString(deletehash)).append("\n");
    sb.append("    datetime: ").append(toIndentedString(datetime)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    favorite: ").append(toIndentedString(favorite)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    inGallery: ").append(toIndentedString(inGallery)).append("\n");
    sb.append("    inMostViral: ").append(toIndentedString(inMostViral)).append("\n");
    sb.append("    isAd: ").append(toIndentedString(isAd)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nsfw: ").append(toIndentedString(nsfw)).append("\n");
    sb.append("    section: ").append(toIndentedString(section)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    views: ").append(toIndentedString(views)).append("\n");
    sb.append("    vote: ").append(toIndentedString(vote)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

